name: unique_identifier_3
description: A Flutter plugin for retrieving a device's unique identifier across Android, iOS, Web, macOS, Linux, and Windows platforms.

version: 0.0.1
homepage: https://github.com/jinosh05/unique_identifier_3

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.4.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jinosh.unique_identifier
        pluginClass: UniqueIdentifierPlugin
      ios:
        pluginClass: UniqueIdentifier_3Plugin
      web:
        pluginClass: WebUniqueIdentifierPlugin
        fileName: src/web_unique_identifier.dart
      macos:
        dartPluginClass: MacosUniqueIdentifierPlugin
        fileName: src/macos_unique_identifier.dart
      linux:
        dartPluginClass: LinuxUniqueIdentifierPlugin
        fileName: src/linux_unique_identifier.dart
      windows:
        dartPluginClass: WindowsUniqueIdentifierPlugin
        fileName: src/windows_unique_identifier.dart
