name: unique_identifier_3
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/jinosh05/unique_identifier_3

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jinosh.unique_identifier
        pluginClass: UniqueIdentifierPlugin
      ios:
        pluginClass: UniqueIdentifier_3Plugin
